# List Comprehension
- The syntax for it `Expression for item in iterable`

In [5]:
numbers = []
for num in range(20):
  numbers.append(num)

In [6]:
# Instead of the three codes form before, i can write a list comprehension that does the same thing
number = [x for x in range(20)]

In [8]:
number

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [17]:
numbe = [str(x/2) for x in range(20)] # an operation to each number
# u can use a string instead of the range and it will iterate through it too
numbe

['0.0',
 '0.5',
 '1.0',
 '1.5',
 '2.0',
 '2.5',
 '3.0',
 '3.5',
 '4.0',
 '4.5',
 '5.0',
 '5.5',
 '6.0',
 '6.5',
 '7.0',
 '7.5',
 '8.0',
 '8.5',
 '9.0',
 '9.5']

In [23]:
# Not limited to only lists, can be used with tuples, sets, dicts, strings
string_example = {x for x in 'python'}
string_example

{'h', 'n', 'o', 'p', 't', 'y'}

# Combining lists and loops
- The syntax for it  `Expression for item in iterable if condition == True`

In [25]:
list_jobs = ['Data Analyst', 'Data Science', 'Data Engineer','Business Data Analyst']

In [31]:
analyst_list = []
for job in list_jobs:
  if 'Data Analyst' in job:
    analyst_list.append(job)
# codes from a previous lesson to add data analyst jobs into a new list

In [33]:
analyst_list

['Data Analyst', 'Business Data Analyst']

In [35]:
analyst_list_2 = [job for job in list_jobs if 'Data Analyst' in job]
analyst_list_2
# the same output with list comprehension using less codes

['Data Analyst', 'Business Data Analyst']